services:
  db:
    image: postgres:16
    container_name: uber_db
    environment:
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: uber
      POSTGRES_DB: uber
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uber -d uber"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: